import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;

public class SwingUI {
    JButton render;
    JButton ups;
    JButton rf1;
    JButton lf;
    JButton pop;
    int r = 0;
    int g = 0;
    int b = 0;
    JButton um;
    JButton dm;
    JButton submit;
    JTextField num;
    JButton popFrame;
    JButton buildFrame;
    JButton show;
    JButton saveFrame;
    JLabel header;
    String[] transf = {"Scale", "Move"};
    JComboBox sel;
    JTextField coordorrad;
    JButton adda;
    JLabel animop;
    JLabel list;
    JLabel name;
    JComboBox nt;
    JPanel panel;
    JFrame frame;
    JLabel rgbl;
    JLabel error;
    JTextField rf;
    JTextField gf;
    JTextField bf;
    JLabel fct;
    JButton submit1;
    JButton open;
    JFileChooser chooser;
    JLabel msel;
    JTextField m;
    JButton setm;
    public SwingUI(){
        File folder = new File(Constants.documents);
        File[] listOfFiles = folder.listFiles();
        ArrayList<String> dir = new ArrayList<>();
        for (File file : listOfFiles) {
            if (!file.isFile()) {
                dir.add(file.getName());
            }
        }
        panel = new JPanel();
        panel.setLayout(null);
        frame = new JFrame("Anim8 GUI Window");
        frame.setSize(780,780);
        frame.setVisible(true);
        URL imageURL = Main.class.getClassLoader().getResource("icon.png");
        ImageIcon img = new ImageIcon(imageURL);
        frame.setIconImage(img.getImage());
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.add(panel);
        header = new JLabel("<html><h1>Anim8 Animation Software</h1><h3>Made with Processing.");
        header.setBounds(200, 100, 300, 100);
        header.setVisible(true);
        panel.add(header);
        name = new JLabel("Enter project name");
        name.setBounds(200, 200, 600, 30);
        panel.add(name);
        nt = new JComboBox(dir.toArray(new String[0]));
        nt.setBounds(200, 250, 100, 30);
        panel.add(nt);
        submit = new JButton("Create project");
        submit.setBounds(200, 300, 160, 30);
        submit.addActionListener(new Main());
        panel.add(submit);
        open = new JButton("Open project");
        open.setBounds(200, 350, 160, 30);
        open.addActionListener(new Main());
        panel.add(open);
        rgbl = new JLabel("Enter RGB color below to texture");
        rgbl.setBounds(50, 20, 600, 30);
        rgbl.setVisible(false);
        panel.add(rgbl);
        rf = new JTextField();
        rf.setBounds(50, 50, 100, 30);
        rf.setVisible(false);
        panel.add(rf);
        gf = new JTextField();
        gf.setBounds(50, 90, 100, 30);
        gf.setVisible(false);
        panel.add(gf);
        bf = new JTextField();
        bf.setBounds(50, 130, 100, 30);
        bf.setVisible(false);
        panel.add(bf);
        submit1 = new JButton("Submit");
        submit1.setBounds(50, 170, 100, 30);
        submit1.addActionListener(new Main());
        submit1.setVisible(false);
        panel.add(submit1);
        chooser = new JFileChooser();
        chooser.setDialogTitle("Save project file");
        //
        msel = new JLabel("");
        msel.setBounds(50, 210, 600, 30);
        msel.setVisible(false);
        panel.add(msel);
        m = new JTextField();
        m.setBounds(50, 250, 100, 30);
        m.setVisible(false);
        panel.add(m);
        setm = new JButton("Submit");
        setm.setBounds(50, 290, 100, 30);
        setm.addActionListener(new Main());
        setm.setVisible(false);
        panel.add(setm);
        dm = new JButton("Delete selected");
        dm.setBounds(50, 330, 190, 30);
        dm.addActionListener(new Main());
        dm.setVisible(false);
        panel.add(dm);
        um = new JButton("Update selected");
        um.setBounds(50, 370, 190, 30);
        um.addActionListener(new Main());
        um.setVisible(false);
        panel.add(um);
        //
        render = new JButton("Render animation");
        render.setBounds(270, 380, 190, 30);
        render.addActionListener(new Main());
        render.setVisible(false);
        panel.add(render);
        show = new JButton("Preview animation");
        show.setBounds(270, 420, 190, 30);
        show.addActionListener(new Main());
        show.setVisible(false);
        panel.add(show);
        fct = new JLabel("");
        fct.setBounds(270, -3, 600, 90);
        fct.setVisible(false);
        panel.add(fct);
        animop = new JLabel("<html>Add/remove an animation<br>Type x and y with comma.");
        animop.setBounds(270, 20, 600, 90);
        animop.setVisible(false);
        panel.add(animop);
        sel = new JComboBox(transf);
        sel.setBounds(270, 100, 190, 30);
        sel.setVisible(false);
        panel.add(sel);
        coordorrad = new JTextField();
        coordorrad.setBounds(270, 140, 100, 30);
        coordorrad.setVisible(false);
        panel.add(coordorrad);
        adda = new JButton("Add animation to selected (max 5 animations/frame)");
        adda.setBounds(270, 180, 340, 30);
        adda.addActionListener(new Main());
        adda.setVisible(false);
        panel.add(adda);
        num = new JTextField();
        num.setBounds(270, 220, 100, 30);
        num.setVisible(false);
        panel.add(num);
        popFrame = new JButton("Delete selected");
        popFrame.setBounds(270, 260, 190, 30);
        popFrame.addActionListener(new Main());
        popFrame.setVisible(false);
        panel.add(popFrame);
        buildFrame = new JButton("Merge all into frame");
        buildFrame.setBounds(270, 300, 210, 30);
        buildFrame.addActionListener(new Main());
        buildFrame.setVisible(false);
        panel.add(buildFrame);
        saveFrame = new JButton("Save animations");
        saveFrame.setBounds(270, 340, 210, 30);
        saveFrame.addActionListener(new Main());
        saveFrame.setVisible(false);
        panel.add(saveFrame);
        list = new JLabel("<html>Animations");
        list.setBounds(270, 420, 600, 90);
        list.setVisible(false);
        panel.add(list);
        //
        lf = new JButton("<< Previous");
        lf.setBounds(50, 410, 190, 30);
        lf.addActionListener(new Main());
        lf.setVisible(false);
        panel.add(lf);
        rf1 = new JButton("Next >>");
        rf1.setBounds(50, 450, 190, 30);
        rf1.addActionListener(new Main());
        rf1.setVisible(false);
        rf1.setEnabled(false);
        panel.add(rf1);
        ups = new JButton("Update");
        ups.setBounds(50, 490, 190, 30);
        ups.addActionListener(new Main());
        ups.setVisible(false);
        panel.add(ups);
        pop = new JButton("Delete");
        pop.setBounds(50, 530, 190, 30);
        pop.addActionListener(new Main());
        pop.setVisible(false);
        panel.add(pop);
        //
        error = new JLabel("Error", SwingConstants.CENTER);
        error.setBounds(2, 660, 750, 40);
        error.setBorder(BorderFactory.createLineBorder(Color.red, 5));
        error.setVisible(false);
        error.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                error.setVisible(false);
            }
        });
        panel.add(error);
    }
}
